name: oh
description: oh ORM
version: 0.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.0-99.0.dev

dependencies:
  _fe_analyzer_shared: ^67.0.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
