import 'spec.dart';

class Generated implements Spec {
  /// The generated by default
  final bool byDefault;

  /// The generated always
  final bool always;

  /// The generated identity
  final bool identity;

  /// The generated stored
  final bool stored;

  /// The generated expression
  final Spec? expression;

  /// Creates a generated specification.
  const Generated({
    this.byDefault = false,
    this.always = false,
    this.identity = false,
    this.stored = false,
    this.expression,
  });
}
